// 程式碼區塊語言 → emoji（code block 標頭用）。單獨成檔，避免與元件同檔觸發 fast-refresh 警告。
const LANG_EMOJI: Record<string, string> = {
  javascript: '🟨',
  typescript: '🔷',
  jsx: '⚛️',
  tsx: '⚛️',
  python: '🐍',
  ruby: '💎',
  rust: '🦀',
  go: '🐹',
  java: '☕',
  kotlin: '🟪',
  swift: '🕊️',
  c: '🔵',
  cpp: '🔵',
  csharp: '🟩',
  php: '🐘',
  html: '🌐',
  xml: '📄',
  css: '🎨',
  scss: '🎨',
  sass: '🎨',
  less: '🎨',
  json: '📦',
  json5: '📦',
  jsonc: '📦',
  yaml: '🔧',
  toml: '🔧',
  bash: '💻',
  shell: '💻',
  sh: '💻',
  powershell: '💻',
  sql: '🗄️',
  graphql: '🔺',
  markdown: '📝',
  md: '📝',
  docker: '🐳',
  dockerfile: '🐳',
  make: '🔨',
  makefile: '🔨',
  diff: '±',
  text: '📄',
  // 常見短別名（fence 常直接寫 ```ts / ```js …）
  ts: '🔷',
  js: '🟨',
  py: '🐍',
  rb: '💎',
  rs: '🦀',
  yml: '🔧',
  kt: '🟪',
  cs: '🟩',
  env: '🔧',
  mjs: '🟨',
  cjs: '🟨',
};

export function langEmoji(lang: string): string {
  return LANG_EMOJI[lang.toLowerCase()] ?? '📄';
}
