import { defineConfig } from 'vite-plus';

// Vite+ 的 lint（oxlint）與 fmt（oxfmt）設定，取代原本的 .oxlintrc.json / .oxfmtrc.json。
// 建置與 dev 仍然走 vite.config.start.ts（TanStack Start + Nitro），測試走 vitest.config.ts——
// 這個檔案**只放 lint / fmt**，不要把 build 設定搬進來。
export default defineConfig({
  fmt: {
    printWidth: 120,
    singleQuote: true,
    semi: true,
    ignorePatterns: ['**/*.css', '**/*.json', '**/*.md', 'src/routeTree.gen.ts', 'packages/api-types/index.ts'],
  },
  lint: {
    jsPlugins: [
      {
        name: '@eslint-react',
        specifier: '@eslint-react/eslint-plugin',
      },
      '@shadcn/lint',
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    plugins: ['typescript', 'react', 'unicorn', 'oxc', 'import', 'jsx-a11y', 'promise'],
    ignorePatterns: [
      '.nitro/**',
      '.output/**',
      'build/**',
      'dev-dist/**',
      'dist/**',
      'node_modules/**',
      'packages/*/index.ts',
      'public/**',
      'src/routeTree.gen.ts',
      'stats.html',
      'src/components/ui/**',
      'src/components/animate-ui/**',
      'src/hooks/use-is-in-view.ts',
    ],
    rules: {
      'for-direction': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-constant-binary-expression': 'error',
      'no-constant-condition': [
        'error',
        {
          checkLoops: 'allExceptWhileTrue',
        },
      ],
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-empty': [
        'error',
        {
          allowEmptyCatch: false,
        },
      ],
      'no-empty-character-class': 'error',
      'no-empty-pattern': [
        'error',
        {
          allowObjectPatternsAsParameters: false,
        },
      ],
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': ['error', {}],
      'no-fallthrough': [
        'error',
        {
          allowEmptyCase: false,
          reportUnusedFallthroughComment: false,
        },
      ],
      'no-global-assign': [
        'error',
        {
          exceptions: [],
        },
      ],
      'no-invalid-regexp': ['error', {}],
      'no-irregular-whitespace': [
        'error',
        {
          skipComments: true,
          skipJSXText: true,
          skipRegExps: false,
          skipStrings: true,
          skipTemplates: true,
        },
      ],
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': [
        'error',
        {
          allowEscape: false,
        },
      ],
      'no-nonoctal-decimal-escape': 'error',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': [
        'error',
        {
          props: true,
        },
      ],
      'no-shadow-restricted-names': [
        'error',
        {
          reportGlobalThis: false,
        },
      ],
      'no-sparse-arrays': 'error',
      'no-unexpected-multiline': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-optional-chaining': [
        'error',
        {
          disallowArithmeticOperators: false,
        },
      ],
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': [
        'error',
        {
          allowRegexCharacters: [],
        },
      ],
      'require-yield': 'error',
      'use-isnan': [
        'error',
        {
          enforceForIndexOf: false,
          enforceForSwitchCase: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: false,
        },
      ],
      'react/rules-of-hooks': 'error',
      'react/exhaustive-deps': 'off',
      'react/purity': 'off',
      'react/refs': 'off',
      'react/immutability': 'off',
      'react/preserve-manual-memoization': 'off',
      'react/incompatible-library': 'off',
      // ⚠️ `vp migrate` 會**整批丟掉**它不認識的 plugin 命名空間底下的規則（含 overrides 裡的），
      //    這六條 shadcn/* 就是遷移時被吃掉、事後補回來的。jsPlugins 那邊的註冊還在，
      //    所以 lint 照樣 exit 0——規則沒開而已，完全看不出來。實測是故意塞一個
      //    `bg-[#333]` 的探針檔才發現。再遷移一次記得照樣驗。
      'shadcn/no-raw-colors': 'error',
      'shadcn/no-arbitrary-values': ['error', { allow: ['layout', 'pt-[12vh]'] }],
      'shadcn/no-restyle': [
        'error',
        {
          allow: ['layout'],
          contracts: [
            { pattern: '^Input$', allow: ['layout', 'pl-8', 'pl-9'] },
            { pattern: '^AvatarFallback$', allow: ['layout', 'typography'] },
            { pattern: '^DialogTitle$', allow: ['layout', 'typography'] },
            { pattern: '^FormLabel$', allow: ['layout', 'gap-1.5'] },
          ],
        },
      ],
      'shadcn/require-static-classes': 'error',
      'shadcn/no-inline-styles': 'off',
      'shadcn/no-unknown-classes': 'off',
      'react/only-export-components': [
        'warn',
        {
          allowConstantExport: true,
          allowExportNames: ['Route', 'loader', 'action', 'meta', 'links', 'headers', 'ErrorBoundary', 'clientLoader'],
        },
      ],
      'no-var': 'error',
      'prefer-const': [
        'error',
        {
          destructuring: 'any',
          ignoreReadBeforeAssign: false,
        },
      ],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'typescript/await-thenable': 'error',
      'typescript/ban-ts-comment': 'error',
      'no-array-constructor': 'error',
      'typescript/no-array-delete': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-floating-promises': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-implied-eval': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-assertion': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-assignment': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-enum-comparison': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-unsafe-unary-minus': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: false,
          allowTaggedTemplates: false,
          allowTernary: false,
        },
      ],
      'typescript/no-wrapper-object-types': 'error',
      'typescript/only-throw-error': [
        'error',
        {
          allow: [
            {
              from: 'package',
              name: ['Redirect', 'AnyRedirect', 'NotFoundError'],
              package: '@tanstack/router-core',
            },
          ],
        },
      ],
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/prefer-promise-reject-errors': 'error',
      'typescript/require-await': 'error',
      'typescript/restrict-plus-operands': 'error',
      'typescript/restrict-template-expressions': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/unbound-method': 'error',
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/array-type': 'error',
      'typescript/ban-tslint-comment': 'error',
      'typescript/class-literal-property-style': 'error',
      'typescript/consistent-generic-constructors': 'error',
      'typescript/consistent-indexed-object-style': 'error',
      'typescript/consistent-type-assertions': 'error',
      'typescript/consistent-type-definitions': 'error',
      'typescript/dot-notation': [
        'error',
        {
          allowIndexSignaturePropertyAccess: false,
          allowKeywords: true,
          allowPattern: '',
          allowPrivateClassPropertyAccess: false,
          allowProtectedClassPropertyAccess: false,
        },
      ],
      'typescript/no-confusing-non-null-assertion': 'error',
      'no-empty-function': [
        'error',
        {
          allow: [],
        },
      ],
      'typescript/no-inferrable-types': 'error',
      'typescript/non-nullable-type-assertion-style': 'error',
      'typescript/prefer-find': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-includes': 'error',
      'typescript/prefer-nullish-coalescing': 'error',
      'typescript/prefer-optional-chain': 'error',
      'typescript/prefer-regexp-exec': 'error',
      'typescript/prefer-string-starts-ends-with': 'error',
      '@eslint-react/error-boundaries': 'error',
      '@eslint-react/exhaustive-deps': 'warn',
      '@eslint-react/no-access-state-in-setstate': 'error',
      '@eslint-react/no-array-index-key': 'warn',
      '@eslint-react/no-children-count': 'warn',
      '@eslint-react/no-children-for-each': 'warn',
      '@eslint-react/no-children-map': 'warn',
      '@eslint-react/no-children-only': 'warn',
      '@eslint-react/no-children-to-array': 'warn',
      '@eslint-react/no-clone-element': 'warn',
      '@eslint-react/no-component-will-mount': 'error',
      '@eslint-react/no-component-will-receive-props': 'error',
      '@eslint-react/no-component-will-update': 'error',
      '@eslint-react/no-context-provider': 'warn',
      '@eslint-react/no-create-ref': 'error',
      '@eslint-react/no-direct-mutation-state': 'error',
      '@eslint-react/no-forward-ref': 'warn',
      '@eslint-react/no-missing-key': 'error',
      '@eslint-react/no-nested-component-definitions': 'error',
      '@eslint-react/no-nested-lazy-component-declarations': 'error',
      '@eslint-react/no-set-state-in-component-did-mount': 'warn',
      '@eslint-react/no-set-state-in-component-did-update': 'warn',
      '@eslint-react/no-set-state-in-component-will-update': 'warn',
      '@eslint-react/no-unnecessary-use-prefix': 'warn',
      '@eslint-react/no-unsafe-component-will-mount': 'warn',
      '@eslint-react/no-unsafe-component-will-receive-props': 'warn',
      '@eslint-react/no-unsafe-component-will-update': 'warn',
      '@eslint-react/no-unused-class-component-members': 'warn',
      '@eslint-react/no-use-context': 'warn',
      '@eslint-react/purity': 'warn',
      '@eslint-react/rules-of-hooks': 'error',
      '@eslint-react/set-state-in-effect': 'warn',
      '@eslint-react/set-state-in-render': 'error',
      '@eslint-react/static-components': 'error',
      '@eslint-react/unsupported-syntax': 'error',
      '@eslint-react/use-memo': 'error',
      '@eslint-react/use-state': 'warn',
      '@eslint-react/jsx-no-children-prop': 'warn',
      '@eslint-react/jsx-no-children-prop-with-children': 'error',
      '@eslint-react/jsx-no-comment-textnodes': 'warn',
      '@eslint-react/jsx-no-key-after-spread': 'error',
      '@eslint-react/jsx-no-leaked-dollar': 'warn',
      '@eslint-react/jsx-no-leaked-semicolon': 'warn',
      '@eslint-react/jsx-no-namespace': 'error',
      '@eslint-react/rsc-function-definition': 'error',
      '@eslint-react/dom-no-dangerously-set-innerhtml': 'warn',
      '@eslint-react/dom-no-dangerously-set-innerhtml-with-children': 'error',
      '@eslint-react/dom-no-find-dom-node': 'error',
      '@eslint-react/dom-no-flush-sync': 'error',
      '@eslint-react/dom-no-hydrate': 'error',
      '@eslint-react/dom-no-render': 'error',
      '@eslint-react/dom-no-render-return-value': 'error',
      '@eslint-react/dom-no-script-url': 'warn',
      '@eslint-react/dom-no-unsafe-iframe-sandbox': 'warn',
      '@eslint-react/dom-no-use-form-state': 'error',
      '@eslint-react/dom-no-void-elements-with-children': 'error',
      '@eslint-react/web-api-no-leaked-event-listener': 'warn',
      '@eslint-react/web-api-no-leaked-fetch': 'warn',
      '@eslint-react/web-api-no-leaked-intersection-observer': 'warn',
      '@eslint-react/web-api-no-leaked-interval': 'warn',
      '@eslint-react/web-api-no-leaked-resize-observer': 'warn',
      '@eslint-react/web-api-no-leaked-timeout': 'warn',
      '@eslint-react/naming-convention-context-name': 'warn',
      '@eslint-react/naming-convention-id-name': 'warn',
      '@eslint-react/naming-convention-ref-name': 'warn',
      'typescript/consistent-type-imports': 'error',
      'typescript/no-non-null-assertion': 'warn',
      'typescript/no-unnecessary-condition': 'warn',
      'typescript/no-meaningless-void-operator': 'off',
      'promise/no-callback-in-promise': 'off',
      'unicorn/no-useless-fallback-in-spread': 'off',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: [
          'src/components/layout/NotFound.tsx',
          'src/components/common/BrandIcons.tsx',
          'src/components/common/SignatureSVG.tsx',
          'src/components/media/ZeroGravityLibrary.tsx',
        ],
        rules: { 'shadcn/no-raw-colors': 'off' },
      },
      {
        files: ['src/routes/**', 'src/i18n/localePage.tsx'],
        rules: {
          'react/only-export-components': 'off',
        },
      },
      {
        files: ['**/*.cjs', '*.config.js', 'scripts/**/*.cjs'],
        rules: {
          'typescript/no-require-imports': 'off',
        },
      },
      {
        // JS 檔沒有型別註記，這幾條看到的全是推斷或 any——實測 4 支 .mjs 冒出 98 筆，
        // 沒有一筆是能照著修的真問題。其餘型別感知規則（no-floating-promises 等）照常生效。
        files: ['**/*.mjs', '**/*.cjs', '**/*.js'],
        rules: {
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-member-access': 'off',
          'typescript/no-unsafe-call': 'off',
          'typescript/no-unsafe-return': 'off',
          'typescript/no-unsafe-argument': 'off',
          'typescript/restrict-template-expressions': 'off',
          'typescript/no-unnecessary-condition': 'off',
          'typescript/require-array-sort-compare': 'off',
        },
      },
    ],
    // ⚠️ 刻意不設 `options.typeAware` / `typeCheck`（`vp migrate` 會自己加上去）。
    //    型別感知只對 src 開，由 CI 那條指令的 `--type-aware` 決定；設成全域的話
    //    scripts / server / packages 會一起變成型別感知，行為就不是遷移前那樣了。
    //    typeCheck 等於再跑一次 tsc，而 tsc 本來就是獨立的門檻。
  },
});
