// 由 backend `cargo run --bin export_types` 產生 — 勿手改

// This file has been generated by Specta. Do not edit this file manually.
/**  `GET /api/admin/categories`（requireAdmin）。裸陣列。admin 版含 created_at、且 JOIN 不過濾 status。 */
export type AdminCategoryRow = {
	id: number,
	name: string,
	slug: string,
	description: string | null,
	short_description: string | null,
	created_at: string,
	updated_at: string | null,
	post_count: number,
};

/**  `GET /api/admin/tags` 單列（admin 版：含 0 篇的 tag、依名排序）。 */
export type AdminTagRow = {
	id: number,
	name: string,
	created_at: string,
	post_count: number,
};

/**  `GET /api/admin/users`（**requireOwner**）。`{ users: [...] }`，顯式欄位。 */
export type AdminUserRow = {
	id: number,
	provider: string | null,
	provider_id: string | null,
	display_name: string | null,
	email: string | null,
	avatar_url: string | null,
	role: string | null,
	linked_to: number | null,
	created_at: string | null,
	updated_at: string | null,
};

export type AdminUsersResponse = {
	users: AdminUserRow[],
};
