/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThinkingRouteImport } from './routes/thinking'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CinemaRouteImport } from './routes/cinema'
import { Route as BookshelfRouteImport } from './routes/bookshelf'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIndexRouteImport } from './routes/watch/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as WatchLibraryRouteImport } from './routes/watch/library'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as LocaleThinkingRouteImport } from './routes/$locale/thinking'
import { Route as LocaleSetupRouteImport } from './routes/$locale/setup'
import { Route as LocalePortfolioRouteImport } from './routes/$locale/portfolio'
import { Route as LocaleMusicRouteImport } from './routes/$locale/music'
import { Route as LocaleMessagesRouteImport } from './routes/$locale/messages'
import { Route as LocaleFriendsRouteImport } from './routes/$locale/friends'
import { Route as LocaleCinemaRouteImport } from './routes/$locale/cinema'
import { Route as LocaleBookshelfRouteImport } from './routes/$locale/bookshelf'
import { Route as LocaleAnimeRouteImport } from './routes/$locale/anime'
import { Route as LocaleActivityRouteImport } from './routes/$locale/activity'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleWatchIndexRouteImport } from './routes/$locale/watch/index'
import { Route as LocaleWatchLibraryRouteImport } from './routes/$locale/watch/library'
import { Route as LocaleBlogIdRouteImport } from './routes/$locale/blog/$id'

const ThinkingRoute = ThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaRoute = CinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const BookshelfRoute = BookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLibraryRoute = WatchLibraryRouteImport.update({
  id: '/watch/library',
  path: '/watch/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleThinkingRoute = LocaleThinkingRouteImport.update({
  id: '/$locale/thinking',
  path: '/$locale/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSetupRoute = LocaleSetupRouteImport.update({
  id: '/$locale/setup',
  path: '/$locale/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePortfolioRoute = LocalePortfolioRouteImport.update({
  id: '/$locale/portfolio',
  path: '/$locale/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMusicRoute = LocaleMusicRouteImport.update({
  id: '/$locale/music',
  path: '/$locale/music',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMessagesRoute = LocaleMessagesRouteImport.update({
  id: '/$locale/messages',
  path: '/$locale/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleFriendsRoute = LocaleFriendsRouteImport.update({
  id: '/$locale/friends',
  path: '/$locale/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCinemaRoute = LocaleCinemaRouteImport.update({
  id: '/$locale/cinema',
  path: '/$locale/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBookshelfRoute = LocaleBookshelfRouteImport.update({
  id: '/$locale/bookshelf',
  path: '/$locale/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAnimeRoute = LocaleAnimeRouteImport.update({
  id: '/$locale/anime',
  path: '/$locale/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleActivityRoute = LocaleActivityRouteImport.update({
  id: '/$locale/activity',
  path: '/$locale/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWatchIndexRoute = LocaleWatchIndexRouteImport.update({
  id: '/$locale/watch/',
  path: '/$locale/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWatchLibraryRoute = LocaleWatchLibraryRouteImport.update({
  id: '/$locale/watch/library',
  path: '/$locale/watch/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIdRoute = LocaleBlogIdRouteImport.update({
  id: '/$locale/blog/$id',
  path: '/$locale/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/anime': typeof AnimeRoute
  '/bookshelf': typeof BookshelfRoute
  '/cinema': typeof CinemaRoute
  '/friends': typeof FriendsRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/thinking': typeof ThinkingRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/anime': typeof LocaleAnimeRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/cinema': typeof LocaleCinemaRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/thinking': typeof LocaleThinkingRoute
  '/blog/$id': typeof BlogIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/$locale/watch/': typeof LocaleWatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/anime': typeof AnimeRoute
  '/bookshelf': typeof BookshelfRoute
  '/cinema': typeof CinemaRoute
  '/friends': typeof FriendsRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/thinking': typeof ThinkingRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/anime': typeof LocaleAnimeRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/cinema': typeof LocaleCinemaRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/thinking': typeof LocaleThinkingRoute
  '/blog/$id': typeof BlogIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale': typeof LocaleIndexRoute
  '/watch': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/$locale/watch': typeof LocaleWatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/anime': typeof AnimeRoute
  '/bookshelf': typeof BookshelfRoute
  '/cinema': typeof CinemaRoute
  '/friends': typeof FriendsRoute
  '/messages': typeof MessagesRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/setup': typeof SetupRoute
  '/thinking': typeof ThinkingRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/activity': typeof LocaleActivityRoute
  '/$locale/anime': typeof LocaleAnimeRoute
  '/$locale/bookshelf': typeof LocaleBookshelfRoute
  '/$locale/cinema': typeof LocaleCinemaRoute
  '/$locale/friends': typeof LocaleFriendsRoute
  '/$locale/messages': typeof LocaleMessagesRoute
  '/$locale/music': typeof LocaleMusicRoute
  '/$locale/portfolio': typeof LocalePortfolioRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/$locale/thinking': typeof LocaleThinkingRoute
  '/blog/$id': typeof BlogIdRoute
  '/watch/library': typeof WatchLibraryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
  '/$locale/watch/library': typeof LocaleWatchLibraryRoute
  '/$locale/watch/': typeof LocaleWatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/anime'
    | '/bookshelf'
    | '/cinema'
    | '/friends'
    | '/messages'
    | '/music'
    | '/portfolio'
    | '/setup'
    | '/thinking'
    | '/$locale/about'
    | '/$locale/activity'
    | '/$locale/anime'
    | '/$locale/bookshelf'
    | '/$locale/cinema'
    | '/$locale/friends'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/thinking'
    | '/blog/$id'
    | '/watch/library'
    | '/$locale/'
    | '/watch/'
    | '/$locale/blog/$id'
    | '/$locale/watch/library'
    | '/$locale/watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/anime'
    | '/bookshelf'
    | '/cinema'
    | '/friends'
    | '/messages'
    | '/music'
    | '/portfolio'
    | '/setup'
    | '/thinking'
    | '/$locale/about'
    | '/$locale/activity'
    | '/$locale/anime'
    | '/$locale/bookshelf'
    | '/$locale/cinema'
    | '/$locale/friends'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/thinking'
    | '/blog/$id'
    | '/watch/library'
    | '/$locale'
    | '/watch'
    | '/$locale/blog/$id'
    | '/$locale/watch/library'
    | '/$locale/watch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/anime'
    | '/bookshelf'
    | '/cinema'
    | '/friends'
    | '/messages'
    | '/music'
    | '/portfolio'
    | '/setup'
    | '/thinking'
    | '/$locale/about'
    | '/$locale/activity'
    | '/$locale/anime'
    | '/$locale/bookshelf'
    | '/$locale/cinema'
    | '/$locale/friends'
    | '/$locale/messages'
    | '/$locale/music'
    | '/$locale/portfolio'
    | '/$locale/setup'
    | '/$locale/thinking'
    | '/blog/$id'
    | '/watch/library'
    | '/$locale/'
    | '/watch/'
    | '/$locale/blog/$id'
    | '/$locale/watch/library'
    | '/$locale/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AnimeRoute: typeof AnimeRoute
  BookshelfRoute: typeof BookshelfRoute
  CinemaRoute: typeof CinemaRoute
  FriendsRoute: typeof FriendsRoute
  MessagesRoute: typeof MessagesRoute
  MusicRoute: typeof MusicRoute
  PortfolioRoute: typeof PortfolioRoute
  SetupRoute: typeof SetupRoute
  ThinkingRoute: typeof ThinkingRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleActivityRoute: typeof LocaleActivityRoute
  LocaleAnimeRoute: typeof LocaleAnimeRoute
  LocaleBookshelfRoute: typeof LocaleBookshelfRoute
  LocaleCinemaRoute: typeof LocaleCinemaRoute
  LocaleFriendsRoute: typeof LocaleFriendsRoute
  LocaleMessagesRoute: typeof LocaleMessagesRoute
  LocaleMusicRoute: typeof LocaleMusicRoute
  LocalePortfolioRoute: typeof LocalePortfolioRoute
  LocaleSetupRoute: typeof LocaleSetupRoute
  LocaleThinkingRoute: typeof LocaleThinkingRoute
  BlogIdRoute: typeof BlogIdRoute
  WatchLibraryRoute: typeof WatchLibraryRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
  LocaleBlogIdRoute: typeof LocaleBlogIdRoute
  LocaleWatchLibraryRoute: typeof LocaleWatchLibraryRoute
  LocaleWatchIndexRoute: typeof LocaleWatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thinking': {
      id: '/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof ThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema': {
      id: '/cinema'
      path: '/cinema'
      fullPath: '/cinema'
      preLoaderRoute: typeof CinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookshelf': {
      id: '/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof BookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/library': {
      id: '/watch/library'
      path: '/watch/library'
      fullPath: '/watch/library'
      preLoaderRoute: typeof WatchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/thinking': {
      id: '/$locale/thinking'
      path: '/$locale/thinking'
      fullPath: '/$locale/thinking'
      preLoaderRoute: typeof LocaleThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/setup': {
      id: '/$locale/setup'
      path: '/$locale/setup'
      fullPath: '/$locale/setup'
      preLoaderRoute: typeof LocaleSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/portfolio': {
      id: '/$locale/portfolio'
      path: '/$locale/portfolio'
      fullPath: '/$locale/portfolio'
      preLoaderRoute: typeof LocalePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/music': {
      id: '/$locale/music'
      path: '/$locale/music'
      fullPath: '/$locale/music'
      preLoaderRoute: typeof LocaleMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/messages': {
      id: '/$locale/messages'
      path: '/$locale/messages'
      fullPath: '/$locale/messages'
      preLoaderRoute: typeof LocaleMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/friends': {
      id: '/$locale/friends'
      path: '/$locale/friends'
      fullPath: '/$locale/friends'
      preLoaderRoute: typeof LocaleFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/cinema': {
      id: '/$locale/cinema'
      path: '/$locale/cinema'
      fullPath: '/$locale/cinema'
      preLoaderRoute: typeof LocaleCinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/bookshelf': {
      id: '/$locale/bookshelf'
      path: '/$locale/bookshelf'
      fullPath: '/$locale/bookshelf'
      preLoaderRoute: typeof LocaleBookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/anime': {
      id: '/$locale/anime'
      path: '/$locale/anime'
      fullPath: '/$locale/anime'
      preLoaderRoute: typeof LocaleAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/activity': {
      id: '/$locale/activity'
      path: '/$locale/activity'
      fullPath: '/$locale/activity'
      preLoaderRoute: typeof LocaleActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/watch/': {
      id: '/$locale/watch/'
      path: '/$locale/watch'
      fullPath: '/$locale/watch/'
      preLoaderRoute: typeof LocaleWatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/watch/library': {
      id: '/$locale/watch/library'
      path: '/$locale/watch/library'
      fullPath: '/$locale/watch/library'
      preLoaderRoute: typeof LocaleWatchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$id': {
      id: '/$locale/blog/$id'
      path: '/$locale/blog/$id'
      fullPath: '/$locale/blog/$id'
      preLoaderRoute: typeof LocaleBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AnimeRoute: AnimeRoute,
  BookshelfRoute: BookshelfRoute,
  CinemaRoute: CinemaRoute,
  FriendsRoute: FriendsRoute,
  MessagesRoute: MessagesRoute,
  MusicRoute: MusicRoute,
  PortfolioRoute: PortfolioRoute,
  SetupRoute: SetupRoute,
  ThinkingRoute: ThinkingRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleActivityRoute: LocaleActivityRoute,
  LocaleAnimeRoute: LocaleAnimeRoute,
  LocaleBookshelfRoute: LocaleBookshelfRoute,
  LocaleCinemaRoute: LocaleCinemaRoute,
  LocaleFriendsRoute: LocaleFriendsRoute,
  LocaleMessagesRoute: LocaleMessagesRoute,
  LocaleMusicRoute: LocaleMusicRoute,
  LocalePortfolioRoute: LocalePortfolioRoute,
  LocaleSetupRoute: LocaleSetupRoute,
  LocaleThinkingRoute: LocaleThinkingRoute,
  BlogIdRoute: BlogIdRoute,
  WatchLibraryRoute: WatchLibraryRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
  LocaleBlogIdRoute: LocaleBlogIdRoute,
  LocaleWatchLibraryRoute: LocaleWatchLibraryRoute,
  LocaleWatchIndexRoute: LocaleWatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
