/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as LocaleSetupRouteImport } from './routes/$locale/setup'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleBlogIdRouteImport } from './routes/$locale/blog/$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSetupRoute = LocaleSetupRouteImport.update({
  id: '/$locale/setup',
  path: '/$locale/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBlogIdRoute = LocaleBlogIdRouteImport.update({
  id: '/$locale/blog/$id',
  path: '/$locale/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup': typeof SetupRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/blog/$id': typeof BlogIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup': typeof SetupRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/blog/$id': typeof BlogIdRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setup': typeof SetupRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/setup': typeof LocaleSetupRoute
  '/blog/$id': typeof BlogIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$id': typeof LocaleBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/setup'
    | '/$locale/about'
    | '/$locale/setup'
    | '/blog/$id'
    | '/$locale/'
    | '/$locale/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/setup'
    | '/$locale/about'
    | '/$locale/setup'
    | '/blog/$id'
    | '/$locale'
    | '/$locale/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/setup'
    | '/$locale/about'
    | '/$locale/setup'
    | '/blog/$id'
    | '/$locale/'
    | '/$locale/blog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SetupRoute: typeof SetupRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleSetupRoute: typeof LocaleSetupRoute
  BlogIdRoute: typeof BlogIdRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogIdRoute: typeof LocaleBlogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/setup': {
      id: '/$locale/setup'
      path: '/$locale/setup'
      fullPath: '/$locale/setup'
      preLoaderRoute: typeof LocaleSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/blog/$id': {
      id: '/$locale/blog/$id'
      path: '/$locale/blog/$id'
      fullPath: '/$locale/blog/$id'
      preLoaderRoute: typeof LocaleBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SetupRoute: SetupRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleSetupRoute: LocaleSetupRoute,
  BlogIdRoute: BlogIdRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogIdRoute: LocaleBlogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
